### PR TITLE
Remove explicit reference of System.Xml.XDocument.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
It is already covered by .NET Standard 2.0 and including it carries an excessive amount of other redundant dependencies.

### CODE REVIEW

**Comment by Jand42** [comment]
@teo-tsirpanis Hi, can you re-run paket with `.paket/paket update --redirects` to add back the redirects for net4x test projects? Thanks for the submission!

**Comment by teo-tsirpanis** [comment]
Done.

**Comment by Jand42** [comment]
@teo-tsirpanis Built and tested, available on https://daily.websharper.com/nuget and will be on nuget.org in a couple minutes.

**Comment by granicz** [comment]
@teo-tsirpanis Thanks!

**Pull request merged**
